name: Docker Image CI

on:
  push:
   branches:
    - 'master'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN}}

      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          buildder: ${{ steps.builderx.outputs.name}}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/hayes-travel-webscraper:latest
          cache-from: type=registry, ref=${{  secrets.DOCKER_HUB_USERNAME }}/hayes-travel-webscraper:latest
          cache-to: type=registry, ref=${{  secrets.DOCKER_HUB_USERNAME }}/hayes-travel-webscraper:latest
